[ $(which brew) ] && HOMEBREW_PREFIX=$(brew --prefix)

if [[ -f $HOMEBREW_PREFIX/opt/chruby/share/chruby/chruby.sh ]]; then
  source $HOMEBREW_PREFIX/opt/chruby/share/chruby/chruby.sh
  source $HOMEBREW_PREFIX/opt/chruby/share/chruby/auto.sh
fi
