# Requires "oh-my-zsh" configuration framework for fancyness.
# Upstream: https://github.com/robbyrussell/oh-my-zsh
# Tobi's fork: https://github.com/haelmy/oh-my-zsh

# Load shell agnostic rc files
[ -f $HOME/.shellrc ] && source $HOME/.shellrc
# Load local zsh configuration snippets
[ -f $HOME/.zshrc_local ] && source $HOME/.zshrc_local

# ZSH framework configuration
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="agnoster"

plugins=(brew bundler chruby colored-man git python screen vagrant virtualenvwrapper)

source $ZSH/oh-my-zsh.sh

# Unset or set options differently from oh-my-zsh
unsetopt share_history
setopt interactivecomments

# Set directory colors to match solarized
LSCOLORS=gxfxbEaEBxxEhEhBaDaCaD

# Patch the agnoster prompt
directory_name() {
  if [[ -d $(git rev-parse --show-toplevel 2>/dev/null) ]]; then
    # in a git repository
    git_root=$(git rev-parse --show-toplevel)
    physical_pwd=$(pwd -P)
    path_in_git="${physical_pwd#$git_root}"
    base=$(basename $git_root)

    echo -n $base
    echo -n $path_in_git
  else
    echo '%~'
  fi
}

prompt_dir() {
  prompt_segment blue black $(directory_name)
}
